# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
# Svar.
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)


In [4]:
# nedan tar vi fram information om axes, shape, size och datatype.
print("Dimension:", A.ndim) 
print("Shape:", A.shape) 
print("Size:", A.size)
print("Data type:", A.dtype)

Dimension: 2
Shape: (3, 5)
Size: 15
Data type: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
# Elementwise subtraction.
print(B - C)
print ()

# Elementwise multiplication.
print(B * C)
print ()

# Matrix multiplication. 
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# exponantiate each number elementwise by using (np.exp function). Dessa värden kan visas som felaktiga när man kör "run all" eftersom jag har samma namn på andra konstanter längre ned i koden.
np.exp (B)
print(np.exp(B))
print()

#Calculate the minimum value in the whole matrix.
np.min(B)
print(np.min(B))
print ()

#Minimum value for each row.
B.min(axis=1)
print(B.min(axis=1))
print()

#Minimum value for each column.
B.min(axis=0)
print(B.min(axis=0))
print()

#Find the index value for minimum value for the whole matrix.
np.argmin (B)
print(np.argmin(B))
print()

#Find the index value for minimum value for each row of the matrix.
np.argmin(B.min(axis=1))
print(np.argmin(B, axis=1))
print()

# Sum of all elements.
np.sum(B)
print(np.sum(B))
print()

#mean for each column.
B.mean(axis=0)
print(B.mean(axis=0))
print()

#median for each column.
np.median(B, axis=0)
print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 4 7]

[1 2 3]

0

[0 0 0]

45

[4. 5. 6.]

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [11]:
# i detta fall har vi bara angett en axel vilket ger oss hela mellersta raden enligt ovan. Ska vi ta första raden så sätter vi in 0 och 2 för den tredje. 
# Hade vi exempelvis angett A[1, 4] skulle vi fått rad och index som i detta fall blir 10.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [12]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
# nedan får vi ut arrayen elementvis.
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [15]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [16]:
# Detta ger oss en 1D Array från 0-29
a = np.arange(30)

# Denna kod ger oss samma siffror fast i en 3D-Array vilket man kan se om man kollar på (2, 3, -1) 2:an står för hur många block det delas upp i och 3:an för hur många rader. 
# -1 anger antal kolumner.
b = a.reshape((2, 3, -1))
print(a)

# Mellanrum
print()

print(b)

# Att b har tre axlar innebär alltså att vi har (2, 3, -1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [17]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [18]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [19]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [20]:
def add_mult_matrices(matris1, matris2, operation):
    # kontrollera att det är "np.ndarray"
    if not isinstance(matris1, np.ndarray) or not isinstance(matris2, np.ndarray):
        return "fel: båda värden måste vara numpy arrays"
    
    # här ser vi till att den enbart går att sätta in add eller multiply
    if operation not in ["add", "multiply"]:
        return "fel: enbart add eller multiply gäller."
    
    # kontroll för att matriserna har samma storlek i additionen
    if operation == "add":
        if matris1.shape != matris2.shape:
            return "fel: det måste vara samma form för addition."
        return matris1 + matris2
    
    # kontroll för att matriserna har samma storlek i multiplikationen.
    if operation == "multiply":
        if matris1.shape[1] != matris2.shape[0]: # antal kolumner [1] i den första matrisen och antal rader [0] i matris2 behöver vara samma. 
            return "fel: antal kolumner i 1 måste vara lika med rader i 2."
        return np.dot(matris1, matris2)
    
    # test av koden.
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]]) # här kan man exempelvis sätta in ytterligare värden för att få felmeddelandet "antal nummer i matrix1 måste vara lika med rader i matrix2"
result = add_mult_matrices(m1, m2, 'multiply') # här kan man skriva 'add' eller 'multiply' beroende på önskad operation. Vid fel får man meddelandet "fel: enbart add eller multiply"
print(result)
print()
print(m1 @ m2) # för att säkerställa att vi får samma svar med exepelvis multiplikation.


[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [21]:
# Uppgift 10.1.1. Definiera vektorn x enligt nedan.
# x = (4, 3)
x = np.array([4, 3])
print(x)

# (a) Vilken dimension har vektorn x?
print("dimension:", x.shape)

# (b) Beräkna 5x
print(5 * x)

# (c) Beräkna 3x
print(3 * x)

# (d) Beräkna 5x + 3x
print((5 * x) + (3 * x))

# (e) Beräkna 8x
print(8 * x)

# (f) Beräkna 4x - x

print((4 * x) - x)

# (g) Beräkna x^T, vilken blir den nya dimensionen efter att transponeringen utförts? 
x = x.reshape((-1, 1))
print(x)
print("ny dimension:", x.shape)

# (h) är x + x^T definierat
x = np.array([[4], [3]])

# Transponera x^T (som blir en radvektor)
x_T = x.T
# Detta är inte definierat så jag anväder nedanstående kod för att visa det.
if x_T.shape == x.shape:
    result = x_T + x
    print(result)
else:
    print('ej definierat eftersom dimensionerna inte matchar')

# (i) Beräkna ||x||
norm_x = np.linalg.norm(x)
print(norm_x)


[4 3]
dimension: (2,)
[20 15]
[12  9]
[32 24]
[32 24]
[12  9]
[[4]
 [3]]
ny dimension: (2, 1)
ej definierat eftersom dimensionerna inte matchar
5.0


In [22]:
# uppgift 10.1.2. Definiera vektorn v enligt nedan.
v = np.array([3, 7, 0, 11])
v = v.reshape((-1, 1))
print(v)
print()
# (a) vilken dimension har vektorn
print("dimension:", v.shape)
print()
# (b) beräkna 2v

print(2 * v)
print()

# (c) beräkna 5v + 2v

print((5 * v) + (2 * v))
print()

# (d) beräkna 4v - 2v

print((4 * v) - (2 * v))
print()

# (e) beräkna v^T, vilken blir den nya dimensionen efter att transponeringen utförts?

v = np.array([3, 7, 0, 11])
print("dimension:", v.shape)
print()

# (f) beräkna ||v||
norm_v = np.linalg.norm(v)
print(norm_v)


[[ 3]
 [ 7]
 [ 0]
 [11]]

dimension: (4, 1)

[[ 6]
 [14]
 [ 0]
 [22]]

[[21]
 [49]
 [ 0]
 [77]]

[[ 6]
 [14]
 [ 0]
 [22]]

dimension: (4,)

13.379088160259652


In [23]:
# uppgift 10.1.3. Definiera vektorerna v1 = (4, 3, 1, 5) och v2 = (2, 3, 1, 1)
v1 = np.array([4, 3, 1, 5]) 
v2 = np.array([2, 3, 1, 1])
print(v1)
print(v2)
print()

# (a) beräkna ||v1||

norm_v1 = np.linalg.norm(v1)
print(norm_v1)
print()

# (b) beräkna ||v1 - v2||
norm_diff = np.linalg.norm(v1 - v2)
print(norm_diff)



[4 3 1 5]
[2 3 1 1]

7.14142842854285

4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [24]:
# Uppgift 10.2.1.

A = np.array([2, 1, -1, 1, -1, 1]).reshape(2,3)
B = np.array([4, -2, 1, 2, -4, -2]).reshape(2,3)
C = np.array([1, 2, 2, 1]).reshape(2, 2)
D = np.array([3, 4, 4, 3]).reshape(2, 2)
E = np.array([1, 2]).reshape(-1, 1)
I = np.array([1, 0, 0, 1]).reshape(2, 2)


# (a) 2A
print(2 * A)
print()

# (b) B - 2A
print(B - 2 * A)
print()

# (c) 3C - 2E
print( 3 * C - 2 * E )
print()

# (d) 2D - 3C
print(2 * D - 3 * C)
print()

# (e) D^T + 2D
D_T = D.T

print(2*D + D_T)
print()

# (f) 2C^T - 2D^T
C_T = C.T
D_T = D.T

print(2*C_T - 2*D_T)
print()

# (g) A^T - B
# Detta är inte definierat så jag anväder nedanstående kod för att visa det.
A_T = A.T

if A_T.shape == B.shape:
    result = A_T - B
    print(result)
else:
    print('ej definierat eftersom dimensionerna inte matchar')
print()

# (h) AC
# Ej definierat, samma kod som ovanstående.
if A.shape == C.shape:
    result = A * C
    print(result)
else:
    print('ej definierat eftersom dimensionerna inte matchar')
print()

# (i) CD
print(C @ D)
print()


# (j) CB
print (C @ B)
print()

# (k) CI
print(C @ I)
print()

# (l) AB^T
B_T = B.T

print(A @ B.T)
print()


[[ 4  2 -2]
 [ 2 -2  2]]

[[ 0 -4  3]
 [ 0 -2 -4]]

[[ 1  4]
 [ 2 -1]]

[[3 2]
 [2 3]]

[[ 9 12]
 [12  9]]

[[-4 -4]
 [-4 -4]]

ej definierat eftersom dimensionerna inte matchar

ej definierat eftersom dimensionerna inte matchar

[[11 10]
 [10 11]]

[[  8 -10  -3]
 [ 10  -8   0]]

[[1 2]
 [2 1]]

[[5 2]
 [7 4]]



In [25]:
# Uppgift 10.2.2. Definiera matrisen och beräkna AA^T
A = np.array([2, 3, 4, 5, 4, 1]).reshape(2,3)
print(A)
print()

# Definieras
print("Dimension:", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Data type:", A.dtype)
print()

# Beräkna AA^T
A_T = A.T

print(A @ A.T)
print()

[[2 3 4]
 [5 4 1]]

Dimension: 2
Shape: (2, 3)
Size: 6
Data type: int32

[[29 26]
 [26 42]]



In [26]:
# Uppgift 10.2.3. Definiera matriserna.
A = np.array([1, 2, 2, 4]).reshape(2,2)
B = np.array([2, 1, 1, 3]).reshape(2,2)
C = np.array([4, 3, 0, 2]).reshape(2,2)
print(A)
print()
print(B)
print()
print(C)
print()
# verifiera att AB = AC men att B != C. Vad vi vill demonstrera med detta exemplet är att vi har definierat ett nytt matematiskt objekt (matriser i detta fall) och att de "vanliga reglerna"
# för aritmetik som vi lärt oss från grundskolan inte nödvändigtvis gäller även här.

print(A @ B)
print()
print(A @ C)
print()
# Vi ser tydligt att B != C samtidigt som A*B = A*C. Vet inte om detta är tillräckligt med bevis.

[[1 2]
 [2 4]]

[[2 1]
 [1 3]]

[[4 3]
 [0 2]]

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]



### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [93]:
v1 = np.arange(4)
v2 = v1[-2:]
v3 = v1.copy() # Vi lägger till v3 för att testa hur det skulle se ut med en copy.
print(v1)
print(v2)
print(v3)

# print(v3)

[0 1 2 3]
[2 3]
[0 1 2 3]


In [94]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)
print(v3.base) # tillagt av mig

None
[0 1 2 3]
None


In [95]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
v3[-1] = 123
print(v1)
print(v2)
print(v3) # tillagt av mig

[  0   1   2 123]
[  2 123]
[  0   1   2 123]


In [96]:
# Osäker på om jag har förstått denna fråga rätt men här kommer ett försök på ett svar. Anledningen till att v1 också ändras när man ändrar v2 är att de delar samma data precis som det står skrivet i uppgiften.
# Det kan man även se om man testar med andra värden.
# Vi kan också se skillnaden mellan view och copy. v3 är det jag har lagt till för att vi ska kunna se hur view och copy skiljer sig. 
# vi kan även se ovan att "none" returneras för v3 eftersom det är en copy.